version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thisispass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: sadaat185336@gmail.com
      PGADMIN_DEFAULT_PASSWORD: thisispass
    ports:
      - "80:80"
    depends_on:
      - postgres

